### ISSUE TITLE
only hides on root level - not on store level

### ISSUE THREAD

**Issue by StevenDMbe** [fballiano/openmage-hide-empty-categories#13]
the extension works on "root catalog" level and subcategory level but not on store level.
So if products are in the root catalog of the "all store views" but aren't on the different stores still a category is visible in these stores

**Comment by fballiano** [comment]
as far as I know you can't disable a product for a store/storeview, you can only do that for a website.

I was able to reproduce you problem with a "website" configuration so I'm working on it.

**Comment by fballiano** [comment]
it should be working now with the 0.4.0 release, thank you!
